### ISSUE TITLE
All uefinstall.rst links are broken

### ISSUE THREAD

**Issue by startergo** [chipsec/chipsec#976]
All uefinstall.rst links are broken

**Comment by BrentHoltsclaw** [comment]
Can you elaborate

**Comment by startergo** [comment]
All links here:
https://github.com/chipsec/chipsec/blob/master/docs/sphinx/uefinstall.rst

**Comment by npmitche** [comment]
Should be fixed with https://github.com/chipsec/chipsec/pull/980

**Comment by startergo** [comment]
These links are still broken:
http://edk2.svn.sourceforge.net/svnroot/edk2/trunk/edk2

and
http://sourceforge.net/apps/mediawiki/tianocore/index.php?title=EDKII_EADK

last one probably should point to:
https://sourceforge.net/projects/edk2/files/EDK%20II%20Releases/EADK/EADK_1.02/
but this is from 2013 and you probably mean something newer.

**Comment by frinzell** [comment]
Does #1001  fix the broken links?

**Comment by startergo** [comment]
Yes it does.
